### ISSUE TITLE
why regression loss is not included in the code?

### ISSUE THREAD

**Issue by sungmin9939** [Chris210634/metric-learning-using-contextual-similarity#1]
hi

I'm impressed your wonderful work!

while I am checking your code and paper, what I have found is that regression loss is not applied in the HybridLoss class (the class in 224x224/losses.py file)

Is it just a mistake?

**Comment by Chris210634** [comment]
No, the third loss added to the output of the HybridLoss in the following line of train.py
https://github.com/Chris210634/metric-learning-using-contextual-similarity/blob/8433dcb67c2205c0e30ec07ed1e5b2fb92da016d/224x224/train.py#L305C21-L305C21

**Comment by sungmin9939** [comment]
oh sorry, that was my fault
I was confused by difference of return values between the function "contrastive jaccard" in 224x224/losses.py and metric-learning-using.../losses.py
